export const CATEGORIES = [
  "Adventure", "American Literature", "British Literature", "French Literature", 
  "German Literature", "Russian Literature", "Classics of Literature", "Biographies", 
  "Novels", "Short Stories", "Poetry", "Plays/Films/Dramas", "Romance", 
  "Science-Fiction & Fantasy", "Crime Thrillers & Mystery", "Mythology Legends & Folklore", 
  "Humour", "Children & Young Adult Reading", "Literature - Other", 
  "Engineering & Technology", "Mathematics", "Science - Physics", 
  "Science - Chemistry/Biochemistry", "Science - Biology", "Science - Earth/Agricultural/Farming", 
  "Research Methods/Statistics/Information Sys", "Environmental Issues", "History - American", 
  "History - British", "History - European", "History - Ancient", "History - Medieval/Middle Ages", 
  "History - Early Modern (c. 1450–1750)", "History - Modern (1750+)", "History - Religious", 
  "History - Royalty", "History - Warfare", "History - Schools & Universities", "History - Other", 
  "Archaeology & Anthropology", "Business/Management", "Economics", "Law & Criminology", 
  "Gender & Sexuality Studies", "Psychiatry/Psychology", "Sociology", "Politics", 
  "Parenthood & Family Relations", "Old Age & the Elderly", "Art", "Architecture", "Music", 
  "Fashion", "Journalism/Media/Writing", "Language & Communication", "Essays Letters & Speeches", 
  "Religion/Spirituality", "Philosophy & Ethics", "Cooking & Drinking", "Sports/Hobbies", 
  "How To", "Travel Writing", "Nature/Gardening/Animals", "Sexuality & Erotica", 
  "Health & Medicine", "Drugs/Alcohol/Pharmacology", "Nutrition", 
  "Encyclopedias/Dictionaries/Reference", "Teaching & Education", "Reports & Conference Proceedings", 
  "Journals"
];